### ISSUE TITLE
failed to fetch

### ISSUE THREAD

**Issue by Meeranmk** [safak/nextjs-tutorial#2]
i got unhandleruntime error while fetching the url in blog page

**Comment by chameerapre** [comment]
I have the same issue

**Comment by Meeranmk** [comment]
> I have the same issue
@chameerapre 
export default mongoose.models.Post || mongoose.model("Post",postSchema);

It will work

**Comment by chameerapre** [comment]
Thanks, it works 🙌

**Comment by Meeranmk** [comment]
> Thanks, it works 🙌

@chameerapre 
If you finished the project ping me, i have some bugs on Google login & db etc

**Comment by Sana348** [comment]
> i got unhandleruntime error while fetching the url in blog page

Exactly the same error I got what you done to resolve it?????

**Comment by Meeranmk** [comment]
> > i got unhandleruntime error while fetching the url in blog page
> 
> Exactly the same error I got what you done to resolve it?????


@Sana348 
export default mongoose.models.Post || mongoose.model("Post",postSchema);

It will work

**Comment by Sana348** [comment]
> > > i got unhandleruntime error while fetching the url in blog page
> > 
> > 
> > Exactly the same error I got what you done to resolve it?????
> 
> @Sana348 export default mongoose.models.Post || mongoose.model("Post",postSchema);
> 
> It will work
I ant to connect with you share any id to connect with you please

**Comment by Sana348** [comment]
import React from "react";
import styles from "./page.module.css";
import Link from "next/link";
import Image from "next/image";

async function getData() {
  const res = await fetch("http://localhost:3000/api/posts", {
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

const Blog = async () => {
  const data = await getData();
  return (
    <div className={styles.mainContainer}>
      {data.map((item) => (
        <Link href={`/blog/${item._id}`} className={styles.container} key={item.id}>
          <div className={styles.imageContainer}>
            <Image
              src={item.img}
              alt=""
              width={400}
              height={250}
              className={styles.image}
            />
          </div>
          <div className={styles.content}>
            <h1 className={styles.title}>{item.title}</h1>
            <p className={styles.desc}>{item.desc}</p>
          </div>
        </Link>
      ))}
    </div>
  );
};

export default Blog;

             can you correct this what you were saying

**Comment by Meeranmk** [comment]
> > > > i got unhandleruntime error while fetching the url in blog page
> > > 
> > > 
> > > Exactly the same error I got what you done to resolve it?????
> > 
> > 
> > @Sana348 export default mongoose.models.Post || mongoose.model("Post",postSchema);
> > It will work
> > I ant to connect with you share any id to connect with you please

https://www.linkedin.com/in/meeran-mohideen-455505234/

insta: _meeran_mohideen

**Comment by Sana348** [comment]
> > > > > i got unhandleruntime error while fetching the url in blog page
> > > > 
> > > > 
> > > > Exactly the same error I got what you done to resolve it?????
> > > 
> > > 
> > > @Sana348 export default mongoose.models.Post || mongoose.model("Post",postSchema);
> > > It will work
> > > I ant to connect with you share any id to connect with you please
> 
> https://www.linkedin.com/in/meeran-mohideen-455505234/
> 
> insta: _meeran_mohideen

Kindly accept wanna talk to you

**Comment by Meeranmk** [comment]
> > > > > > i got unhandleruntime error while fetching the url in blog page
> > > > > 
> > > > > 
> > > > > Exactly the same error I got what you done to resolve it?????
> > > > 
> > > > 
> > > > @Sana348 export default mongoose.models.Post || mongoose.model("Post",postSchema);
> > > > It will work
> > > > I ant to connect with you share any id to connect with you please
> > 
> > 
> > https://www.linkedin.com/in/meeran-mohideen-455505234/
> > insta: _meeran_mohideen
> 
> Kindly accept wanna talk to you

Can you share your error as image in LinkedIn
